config/routes.rb
StageLy::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :events
  resources :artists
  resources :venues
  resources :works
  resources :categories
  resources :types
  
  get "static_pages/imprint"
  get 'imprint', to: 'static_pages#imprint', as: 'imprint'

  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :price, :time, :url, :venue_id, :title, :artist_ids, :type_id, :work_ids, :worktitle, :artisttitle, :category_ids, :direct_composer_ids, :subcategory_ids, :composertitle, :soldout, :cancelled
  has_many :performances
  has_many :artists, through: :performances
  has_many :categories_from_artists, through: :artists, :source => :categories
  has_many :occasions
  has_many :works, through: :occasions
  has_many :categories_from_works, through: :works, :source => :categories
  has_many :composers, through: :works
  has_many :event_categories
  has_many :categories, through: :event_categories
  has_many :event_subcategories
  has_many :subcategories, through: :event_subcategories
  has_many :event_composers
  has_many :direct_composers, through: :event_composers, :source => :artist
  has_many :works_events, through: :works, :source => :events
  
  validates_presence_of :venue_id, :time, :type_id

  #default_scope { where("time > ?", Time.now - 1.hours) }

  belongs_to :venue
  belongs_to :type
  before_save :generate_title
  before_save :set_type_to_concert
  before_save :fix_url
  after_save :generate_work
  after_save :generate_artists
  after_save :generate_composers

  after_initialize :set_defaults

  attr_default :time do
    Time.now
  end


  define_index do
    indexes artists.name, :as => :artists
    indexes venue.name, :as => :venue
    indexes categories.name, :as => :categories
    indexes categories_from_works.name, :as => :categories
    indexes categories_from_artists.name, :as => :categories
    indexes type.name, :as => :type
    indexes works.name, :as => :works
    indexes composers.name, :as => :composers
    indexes direct_composers.name, :as => :composers
    indexes subcategories.name, :as => :subcategories

    has time, type_id
    
  end
  #belongs_to :artist, :polymorphic => true

  def generate_title
    if self.works.any?
    workname = self.works.first.name
    elsif self.artists.any?
    workname = self.artists.first.name
    else
    workname = self.type.singular
    end


    
  	self.title = workname + " @ " + self.venue.name
  end

  def set_type_to_concert
    self.type_id =1
  end

  def fix_url
    self.url = self.url.gsub("http://","")
  end

  def generate_work
    if self.worktitle != ""
      work = Work.find_or_create_by_name(self.worktitle)
      work.name = self.worktitle
      work.category_ids = self.category_ids if self.category_ids && work.category_ids.empty?
      work.save!
      Occasion.find_or_create_by_event_id_and_work_id(self.id, work.id)
    end
  end

  def generate_artists
    if self.artisttitle != ""
      artists = self.artisttitle.split(",")
      artists.each do |name|
        artist = Artist.find_or_create_by_name(name)
        artist.name = name
        artist.category_ids = self.category_ids if self.category_ids && artist.category_ids.empty?
        artist.save!
        Performance.find_or_create_by_event_id_and_artist_id(self.id, artist.id)

      end
    end
  end

  def generate_composers
    if self.composertitle != ""
      composers = self.composertitle.split(",")
      composers.each do |name|
        artist = Artist.find_or_create_by_name(name)
        artist.name = name
        artist.category_ids = self.category_ids if self.category_ids && artist.category_ids.empty?
        artist.save!
        EventComposer.find_or_create_by_event_id_and_artist_id(self.id, artist.id)

      end
    end
  end

  def to_param
      
        if works.any?
          this_title = works.first.name
        elsif artists.any?
          this_title = artists.first.name
        else
          this_title = type.singular
        end

    "#{id}-#{this_title.downcase.gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')}-#{venue.name.downcase.gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')}"
  end

    private
      def set_defaults
        self.type_id = 1 if self.new_record?
        #self.time = Time.now if self.new_record?
      end 


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	

	def index
		if params[:q]
				@events = Event.search params[:q], :match_mode => :any, :order => :time,
		  :sort_mode => :asc, :with => {:time => 90.minutes.ago..60.days.from_now, :type_id => 1}
	  	else
			@events = Event.where(:type_id => 1).sort_by(&:time)
		end

		@events = Kaminari.paginate_array(@events).page(params[:page]).per(25)


		#if params[:category]
		#	@category = Category.find(params[:category])
		#	@events = @category.events.sort_by(&:time)
		#end


		#@categories = Category.all.sort_by &:name
	end

	def show
		@event = Event.find(params[:id])
		 
		@same_artists_events = []
		@event.artists.each do |artist|
			@same_artists_events += (artist.events - Array.wrap(@event))
		end
		@same_artists_events = @same_artists_events.uniq.sort_by(&:time).first(10)


		@event_categories = event_categories(@event).uniq

		@same_categories_events = []
			@event_categories.each do |category|
				@same_categories_events += (category_events(category) - Array.wrap(@event))
			end
		@same_categories_events = @same_categories_events.uniq.sort_by(&:time).first(10)

	end




end


 

app/helpers/events_helper.rb
module EventsHelper
	def more_event_titles(event)
		if event.artists.drop(1).any?
		render :partial => 'artists/event_artist', :collection => event.artists.drop(1) 
		else
		""
		end	
	end

	def more_linked_event_titles(event)
		if event.artists.drop(1).any?
		render :partial => 'artists/linked_event_artist', :collection => event.artists.drop(1) 
		else
		""
		end	
	end


	def event_title(event)
				if event.works.any?
					event.works.first.name
				elsif event.artists.any?
					event.artists.first.name + more_event_titles(event)
				else
					event.type.singular
				end
	end

	def german_month(month)
		if month == "1"
			return "Januar"
		elsif month == "2"
			return "Februar"
		elsif month == "3"
			return "Maerz"
		elsif month == "4"
			return "April"
		elsif month == "5"
			return "Mai"
		elsif month == "6"
			return "Juni"
		elsif month == "7"
			return "Juli"
		elsif month == "8"
			return "August"
		elsif month == "9"
			return "September"
		elsif month == "10"
			return "Oktober"
		elsif month == "11"
			return "November"
		elsif month == "12"
			return "Dezember"
		end
	end

	def german_weekday(day)
		if day == "0"
			return "Sonntag"
		elsif day == "1"
			return "Montag"
		elsif day == "2"
			return "Dienstag"
		elsif day == "3"
			return "Mittwoch"
		elsif day == "4"
			return "Donnerstag"
		elsif day == "5"
			return "Freitag"
		elsif day == "6"
			return "Samstag"
		end
	end
		

end

app/views/events/_event.html.erb
<tr onclick="location.href='<%=event_path(event)%>';" style="cursor:pointer">
        <td>
<div id = "event_listing" >
	<div class ="span5">
		<div class="row-fluid">
			
				<% if event.works.any? or event_composers(event).any?%>	
					<div class="span7">
							<div class ="event_details_item"%>
								<% if event.works.any?%>	
								<%= render :partial => 'works/work_blank', :collection =>  event.works %>
								<% elsif event_composers(event).any?%>
								<%= render :partial => 'artists/artist_blank', :collection => event_composers(event).uniq.first(3) %>
								<%= "... " if event_composers(event).uniq.count > 3 %> <br>
								
								<% end %> 
							</div>						
					</div>
				<% end %> 
			


			<div class="span5">
				<% unless event.type.gid == 2 && event.works.any? %>
					<%= render :partial => 'artists/artist_blank', :collection => event.artists %>
				<% end %>
			</div>
		</div>
	</div>




	<% if params[:controller] == "categories" && @category.subcategories.any? %>

		<div class="span2">
			<% if event.subcategories.any? %>
				<%= event.subcategories.uniq.first.name %><%= render event.subcategories.uniq.drop(1) %>
			<% end %>
		</div>

	<%else%>
		<div class="span2">
				<% if event_categories(event) && event_categories(event).uniq.first %>
					<%= event_categories(event).uniq.first.name %><%= render event_categories(event).uniq.drop(1)%> 
				<% end %>

		</div>
	<% end %>


	
	<% unless params[:controller] == "venues"%>
		<div class="span3">
				<div class="hidden-phone">
					<%= event.venue.name unless params[:controller] == "venues"%>
				</div>
		</div>
	<%end%>

	<div class="span2">
		<% if (event.time + 1.hour).today? %>
		<b><%= "Heute" %><br>
		<% elsif (event.time + 1.hour) < Time.now + 6.days %>
		<%= german_weekday(event.time.strftime("%w")) %><br>
		<%else%>
		<%= event.time.strftime("%e. ") + german_month(event.time.strftime("%-m")) %><br>
		<%end%>
		<%= event.time.strftime("%-H:%M Uhr") %></b>
			<b>
						<%= "ausverkauft" if event.soldout? %>
						<%= "abgesagt" if event.cancelled? %> </b>

	</div>
	
</div>
</td>
</tr>

app/views/events/_label_bar.html.erb
<div class ="span5">
	<div class="row-fluid">
		<div class="span7">
			Was
		</div>
		<div class="span5">
		</div>
	</div>
</div>


<div class="span2">
				Genre
</div>

<% unless params[:controller] == "venues"%>
	<div class="span3">
			Ort
	</div>
<%end%>
	
	<div class="span2">
		Beginn
	</div>
	<br>

app/views/events/_mobile_event.html.erb
<tr onclick="location.href='<%=event_path(mobile_event)%>';" style="cursor:pointer">
        <td>
<div class = "very_short_event_listing" >

	<div class="span8">
			<div class ="event_details_item"%>

				<% if mobile_event.works.any?%>	
					
					<%= render :partial => 'works/work_blank', :collection => mobile_event.works %>

				<% elsif mobile_event.type.gid == 1 && event_composers(mobile_event).any?%>
					
					
					<%= render :partial => 'artists/artist_blank', :collection => event_composers(mobile_event).uniq.first(3) %>
					<%= "... " if event_composers(mobile_event).uniq.count > 3 %>
							
				
				<% else %>
					<%= render :partial => 'artists/artist_blank', :collection => mobile_event.artists %>
				
				<% end %> 

		<b>
						<% if mobile_event.soldout? %><%= "ausverkauft" %> <%end%> 
						<% if mobile_event.cancelled? %><%= "abgesagt" %> <%end%> </b>
			</div>
							
	</div>
	<% if params[:controller] == "categories" && @category.subcategories.any? %>
		<% if mobile_event.subcategories.any? %>
		<div class="span2">
			
				<%= mobile_event.subcategories.uniq.first.name %><%= render event.subcategories.uniq.drop(1) %>
			
		</div>
		<% end %>

	<%else%>
	<% if event_categories(mobile_event) && event_categories(mobile_event).uniq.first %>
		<div class="span2">
				
					<%= event_categories(mobile_event).uniq.first.name %><%= render event_categories(mobile_event).uniq.drop(1)%> 
				

		</div>
		<% end %>
	<% end %>
			

	<div class="span4">
				<% if (mobile_event.time + 1.hour).today? %>
		<%= mobile_event.time.strftime("Heute") %><br>
		<% elsif (mobile_event.time + 1.hour) < Time.now + 6.days %>
		<%= german_weekday(mobile_event.time.strftime("%w")) %><br>
		<%else%>
		<%= mobile_event.time.strftime("%e. ") + german_month(mobile_event.time.strftime("%-m"))%><br>
		<%end%>
		<%= mobile_event.time.strftime("%-H:%M Uhr") %>
	</div>


</div>
</td>
</tr>

app/views/events/_short_event.html.erb
<tr onclick="location.href='<%=event_path(short_event)%>';" style="cursor:pointer">
        <td>

<div class = "short_event_listing">

	<div class="span8">
			<div class ="event_details_item"%>
				<%= short_event.venue.name %>
					<b>
						 <% if short_event.soldout? %> <br><%= "ausverkauft"%><%end%>
						<% if short_event.cancelled? %> <br><%= "abgesagt"%><%end%> </b>
			</div>
							
	</div>



	<div class="span4">
		<% if (short_event.time + 1.hour).today? %>
		<%= short_event.time.strftime("Heute, %-H:%M Uhr") %><br>
		<%else%>
		<%= short_event.time.strftime("%e. ") + german_month(short_event.time.strftime("%-m"))%>,
		<%= short_event.time.strftime("%-H:%M Uhr") %><br>
		<%end%>
		

		
	
		
	</div>

	</div>
</div>
</td>
</tr>

app/views/events/_very_short_event.html.erb
<tr onclick="location.href='<%=event_path(very_short_event)%>';" style="cursor:pointer">
        <td>
<div class = "very_short_event_listing" >

	<div class="span8">
			<div class ="event_details_item"%>

				<% if very_short_event.works.any?%>	
					
					<%= render :partial => 'works/work_blank', :collection => very_short_event.works %>

				<% elsif very_short_event.type.gid == 1 && event_composers(very_short_event).any?%>
					
					
					<%= render :partial => 'artists/artist_blank', :collection => event_composers(very_short_event).uniq.first(3) %>
					<%= "... " if event_composers(very_short_event).uniq.count > 3 %> <br>
							
				
				<% else %>
					<%= render :partial => 'artists/artist_blank', :collection => very_short_event.artists %>
				
				<% end %> 

		<b>
						<%= "ausverkauft" if very_short_event.soldout? %>
						<%= "abgesagt" if very_short_event.cancelled? %> </b>
			</div>
							
	</div>
			

	<div class="span4">
				<% if (very_short_event.time + 1.hour).today? %>
		<%= very_short_event.time.strftime("Heute") %><br>
		<% elsif (very_short_event.time + 1.hour) < Time.now + 6.days %>
		<%= german_weekday(very_short_event.time.strftime("%w")) %><br>
		<%else%>
		<%= very_short_event.time.strftime("%e. ") + german_month(very_short_event.time.strftime("%-m"))%><br>
		<%end%>
		<%= very_short_event.time.strftime("%-H:%M Uhr") %>
	</div>


</div>
</td>
</tr>

app/views/events/index.html.erb
<% provide :title, @category.name + " in Lübeck" if @category %>
<% provide :title, params[:q].capitalize + " in Lübeck" if params[:q] %>
<% provide :page_title, @category.name + " in Lübeck" if @category %>
<% provide :page_title, params[:q].capitalize + " in Lübeck" if params[:q] %>
<% provide :keywords, @category.name if @category %>

<div class="visible-phone">
	<div class="mobile_category_menu">
		
		
					<%# if params[:action] == "index" or params[:controller] == "categories" %>

							
							
							
						Alle <%= render :partial => 'categories/button_category', :collection => categories %>
					<%#end%>
		
	</div>
</div>


<div class="hidden-phone">
	<%= render :partial => 'events/label_bar'%>

		<table class="table table-striped">
	  <tbody>
		<%= render @events %>
	  </tbody>
	</table>

</div>

<div class="visible-phone">
		<table class="table table-striped">
	  <tbody>
		<%= render :partial => 'mobile_event', :collection => @events %>
	  </tbody>
	</table>
</div>

	
	 <br>
          <%= paginate @events %>
	


		

app/views/events/show.html.erb
<% provide :title, event_title(@event) + " am " + @event.time.strftime("%e. ") + german_month(@event.time.strftime("%-m")) %>
<% provide :page_title, event_title(@event) + " @ " + @event.venue.name %>
<% (provide :keywords, @event.artists.first.name + more_event_titles(@event) + ", " + @event.venue.name) if @event.artists.any? %>

<div class = "span7">
	<div class="row-fluid">
 			<% if @event.soldout? or @event.cancelled? %>
				<div class ="event_details_item">
					<div class="hidden-phone"><div class ="span1"><i class="icon-exclamation-sign"></i> </div></div>
					<div class ="span11"> <b>
						<%= "Leider ausverkauft!" if @event.soldout? %>
						<%= "Leider abgesagt!" if @event.cancelled? %> </b>
					</div>
				</div>
				<div class="hidden-phone"><br><br></div>
			<% end %>

			<% if @event.works.any? or event_composers(@event).any? %>
				<div class ="event_details_item">
					<div class="hidden-phone"><div class ="span1"><i class="icon-book"></i> </div></div>
					<div class ="span11">
					<% if @event.works.any? %>
						<%= render :partial => 'works/full_work', :collection => @event.works %><br>
					<% end %>
					<% if @event.direct_composers.any? %>Werke von 
						<%= render @event.direct_composers if @event.direct_composers.any? %><br>
					<% end %>
					</div>
				</div>
				<div class="hidden-phone"><br><br></div>
			<% end %> 


			<% if @event.artists.any? %>
				<div class ="event_details_item">
					<div class="hidden-phone"><div class ="span1"><i class="icon-user"></i> </div></div>
					<div class ="span11">
						<%= render @event.artists %>
					</div>
				</div>
				<div class="hidden-phone"><br><br></div>
			<% end %>




			<div class ="event_details_item">
				<div class="hidden-phone"><div class ="span1"><i class="icon-tags"></i> </div></div>
				<div class ="span11">
					<%= @event.type.singular if event_categories(@event).empty? %>	
					<% if event_categories(@event) && event_categories(@event).uniq.first %>
						<%=link_to event_categories(@event).uniq.first.name, event_categories(@event).uniq.first %><%= render event_categories(@event).uniq.drop(1)%> 
				<% end %>
								<% if @event.subcategories.any? %>
					| <%= @event.subcategories.uniq.first.name %><%= render @event.subcategories.uniq.drop(1) %>
				<% end %>
				<br>
					
				
				

				</div>
			</div>
			<div class="hidden-phone"><br><br></div>

			<div class ="event_details_item">
				<div class="hidden-phone"><div class ="span1"><i class="icon-map-marker"></i> </div></div>
				<div class ="span11">
					<%= link_to @event.venue.name, @event.venue %>
					<br>
					<%= @event.venue.address %> <%= link_to "(Karte)","http://maps.google.de/maps?q=#{@event.venue.address}+Lübeck" %>
					<br>
					<%= link_to @event.venue.url, "http://#{@event.venue.url}" %>
					
				</div>
			</div>
			<div class="hidden-phone"><br><br></div><br>

			<div class ="event_details_item">
				<div class="hidden-phone"><div class ="span1"><i class="icon-calendar"></i> </div></div>
				<div class ="span11">
				
		<% if (@event.time + 1.hour).today? %>
		<%= "Heute"%><% else %>
		<%= german_weekday(@event.time.strftime("%w"))%><%end%>,
		<%= @event.time.strftime("%e. ") + german_month(@event.time.strftime("%-m"))%>,
		<%= @event.time.strftime("%-H:%M Uhr") %>
				</div>
			</div>
			<br>
			

			<%if @event.price != "" %>		
				<div class ="event_details_item">	
					<div class="hidden-phone"><div class ="span1"><i class="icon-barcode"></i> </div></div>
					<div class ="span11">
						<%= "Eintritt: " + @event.price %>
					</div>
				</div>
				<div class="hidden-phone"><br><br></div><br>
			<%end%>

			<%if @event.url != "" %>		
				<div class ="event_details_item">	
					<div class="hidden-phone"><div class ="span1"><i class="icon-zoom-in"></i> </div></div>
					<div class ="span11">
						Mehr: <%= link_to truncate(@event.url, :length => 20, :omission =>"...", :separator => ' '), "http://#{@event.url}" %>	
					</div>
				</div>
				<div class="hidden-phone"><br><br></div><br>
			<%end%>
			<br>





			
		


			
			
		
		<% if event_works_events(@event) && event_works_events(@event).any? %>
		<li></li>
			<div class= "same_categories_events">
					<div class = "event_bar">
						<div class="span10">
							Andere Termine für das gleiche Konzert in Lübeck:
							
						</div>
					</div>
					<br><br><br>


					<table class="table table-striped">
					  <tbody>
						<%= render :partial => 'short_event', :collection => event_works_events(@event) %>
					</tbody>
					</table>
			</div>
		<%end%>	
	</div>	
</div>

		
<% if @same_categories_events.any? %>
	<div class = "span5">
			<div class="visible-phone"><li></li></div>

						
								Andere <%= link_to @event_categories.first.name, @event_categories.first %><%= render @event_categories.drop(1) %> Konzerte in Lübeck:
								<br><br><br>
							<table class="table table-striped">
							  <tbody>
								<%= render :partial => 'very_short_event', :collection => @same_categories_events %>
							  </tbody>
							</table>
							<%= link_to "Mehr " +  @event_categories.first.name + " Konzerte >>",  @event_categories.first %>

			</div>
	</div>
<%end%>

		

	



	


	