config/routes.rb
StageLy::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :events
  resources :artists
  resources :venues
  resources :works
  resources :categories
  resources :types
  
  get "static_pages/imprint"
  get 'imprint', to: 'static_pages#imprint', as: 'imprint'

  root :to => 'events#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :type_id
  has_many :affinities
  has_many :artists, through: :affinities
  has_many :events_from_artists, through: :artists, :source => :events
  has_many :work_categories
  has_many :works, :through => :work_categories
  has_many :events_from_works, through: :works, :source => :events
  has_many :event_categories
  has_many :events, through: :event_categories
  has_many :subcategories
  belongs_to :type

  validates_uniqueness_of :name, :case_sensitive => false
  default_scope order: 'categories.name ASC'


  def to_param
  	"#{id}-#{name.downcase.gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')}-luebeck"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
			@category = Category.find(params[:id])
			#@events = Event.search :conditions => {:categories => @category.name}, :match_mode => :any, :order => :time,
		  #:sort_mode => :asc
			#if params[:type]
				@type = Type.find(1)
			#	@type_events = @type.events.uniq.sort_by(&:time)
				@events = category_events(@category).select { |event| event.type_id == @type.id}.uniq.sort_by(&:time)
			#	@type_categories = @type.categories.sort_by(&:name)
			#else
			
			#	@events = category_events(@category).uniq.sort_by(&:time)
			#	@type_events = @events
			#end

			@events = Kaminari.paginate_array(@events).page(params[:page]).per(25)
			
			
			#@type_categories=[]

			#@type_events.each do |event|
			#	@type_categories += event_categories(event)
			#end


	end



end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_button_category.html.erb
<% if button_category.id == params[:id].to_i  && params[:controller] == "categories" %> | <%= button_category.name%><% else %> | <%=link_to button_category.name, button_category %><% end %>

app/views/categories/_category.html.erb
, <% if params[:controller] == "events" && params[:action] == "show" %> 
 <%=link_to category.name, category_path(category) %>
 <%else%><%=category.name%><% end %>

app/views/categories/_menu_category.html.erb
<br>
<% if menu_category.id == params[:id].to_i && params[:controller] == "categories" %>
	<b><%= menu_category.name %></b>
<% else %> 
<%=link_to menu_category.name, category_path(menu_category) %>
<% end %>

app/views/categories/show.html.erb
<% provide :title, @category.name + " in Lübeck" %>
<% provide :page_title, @category.name + " in Lübeck" %>
<% provide :keywords, @category.name %>
<div class="visible-phone">
	<div class="mobile_category_menu">
		
		
					<%# if params[:action] == "index" or params[:controller] == "categories" %>
						
							<%= link_to "Alle", root_path %> <%= render :partial => 'categories/button_category', :collection => categories %>

					<%#end%>
		
	</div>
</div>
<div class="hidden-phone">
	<%= render :partial => 'events/label_bar'%>

		<table class="table table-striped">
	  <tbody>
		<%= render @events %>
	  </tbody>
	</table>

</div>

<div class="visible-phone">
		<table class="table table-striped">
	  <tbody>
		<%= render :partial => 'events/very_short_event', :collection => @events %>
	  </tbody>
	</table>
</div>

	 <br>
          <%= paginate @events %>