config/routes.rb
StageLy::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :events
  resources :artists
  resources :venues
  resources :works
  resources :categories
  resources :types
  
  get "static_pages/imprint"
  get 'imprint', to: 'static_pages#imprint', as: 'imprint'

  root :to => 'events#index'

end

app/views/layouts/_menu.html.erb
<div class="span2">
			<div class="category_menu">
				<%# if params[:action] == "index" or params[:controller] == "categories" %>
					<% unless params[:controller] == "events" && params[:action] == "index" %>
						<%= link_to "Alles", root_path %>
						<%else%>
						<%= "Alles" %>
						<%end%>
						
					<%= render :partial => 'categories/menu_category', :collection => categories %>
				<%#end%>
			</div>
</div> 	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_slogan(yield(:page_title)).html_safe %> - stage.ly</title>
   <meta name="description" content="<%= full_slogan(yield(:page_title)).html_safe %>"/>     
    <meta name="keywords" content="<%= yield(:keywords).html_safe + ", " + "Lübeck, Konzerte, Concerts"%>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  var pluginUrl = 
 '//www.google-analytics.com/plugins/ga/inpage_linkid.js';
_gaq.push(['_require', 'inpage_linkid', pluginUrl]);
  _gaq.push(['_setAccount', 'UA-30268380-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<meta property="fb:admins" content="568790501" />
<meta name="google-site-verification" content="CK67_-a5FPbjRusxNraAhs28Qss5hc7o_EdDh9EycgI" />
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
	<header>
		 <div class="container-fluid">
			<div class="row-fluid">
				<div class = "span2">
						<div class='logo'>
							<%= image_tag('/eighth-notes-logo-big.png') %>
							<%= link_to "stage.ly", root_path %>
						</div>
				</div>	
				<div class ="span8">
					<div class="row-fluid">
						
							<div class ="span8">
								<div class="hidden-phone">
								<div class='slogan'>
									<% if @event && @event.url != "" %>
									<%= link_to full_slogan(yield(:title)).html_safe, "http://#{@event.url}" %>
									<% else %>
									<%= full_slogan(yield(:title)).html_safe %>
									<%end%>
								</div>
								</div>
							</div>
							<div class ="span4">
								<div class="search_box">
				                    <%= form_tag events_path, :method => 'get' do %>
				                      <%= text_field_tag :q, nil, :placeholder => 'Suche Konzerte ...'%>
			                    	<% end %>
			                  	</div>
              				</div>
              				<br>
              				<div class="visible-phone">
								<div class='slogan'>
									<% if @event && @event.url != "" %>
									<%= link_to full_slogan(yield(:title)).html_safe, "http://#{@event.url}" %>
									<% else %>
									<%= full_slogan(yield(:title)).html_safe %>
									<%end%>
								</div>
								</div>
              				<div class="row-fluid">
							<div class="hidden-phone"><div class="fb-like span8" data-send="true" data-width="240" data-show-faces="false"></div></div>
							</div>	
				
					</div>
				</div>					
			</div>
		</div>
	</header>
 <div class="container-fluid">
	<div class="row-fluid"> 
		 <div class="hidden-phone">
		 	<%= render 'layouts/menu'%>	
		</div>
		<div class="span8">
			<div class="row-fluid">
				<%= yield %>
			</div>
		</div> 
	</div>
</div>




<footer>
	<div class="container-fluid">
		<div class="row-fluid">
			<div class ="span2"%></div>
			<div class="span8">
				<b><%= mail_to "stage.ly@gmail.com", "Fehlt ein Konzert? / Konzert hinzufügen!", :subject => 'fehlendes Konzert!', :class=> 'sea_green' %></b><br><br>
				<%= mail_to "stage.ly@gmail.com", "Feedback", :subject => 'Feedback', :class=> 'sea_green' %>  ·  <%= link_to "Impressum", imprint_path %> · (c) stage.ly
			</div>
		</div>
	</div>
</footer>
</body>

</html>